#!/bin/bash

REPO_URL="https://github.com/DansDesigns/Alternix.git"
VERSION_URL="https://raw.githubusercontent.com/DansDesigns/Alternix/refs/heads/main/update/version.txt"

LOCAL_VERSION=$(cat /usr/share/alternix/version.txt 2>/dev/null)
REMOTE_VERSION=$(curl -fs $VERSION_URL)


if [ -z "$REMOTE_VERSION" ]; then
    echo " "
    echo "[------ERROR------]"
    echo "Unable to check for updates.."
    echo "Check Internet Connection.."
    echo " "
    exit 1
fi

if dpkg --compare-versions "$REMOTE_VERSION" gt "$LOCAL_VERSION"; then
    echo " "
    echo "Current Version: $LOCAL_VERSION"
    echo " "
    echo "New version available: $REMOTE_VERSION"
    echo " "
    echo " "
    echo "Downloading Update..."
    echo " "
    echo " "
    echo " "

    git clone "$REPO_URL" || exit 1
    cd "$REPO_URL"

    chmod +x install-update.sh
    sudo ./install-update.sh

    echo "New Version: $REMOTE_VERSION" | sudo tee /usr/share/alternix/version.txt

    cd $HOME
    rm -r "$REPO_URL"

    echo "Update complete."
else
    echo "Alternix is up to date."
fi