#!/bin/bash



echo "=============================================="
echo "          Alternix Desktop Updater"
echo "=============================================="
echo "-------> Teaching Penguins to fly! <-------"
echo " "
sleep 2
echo "Checking for Update..."
echo " "
echo " "
sleep 2

REPO_URL="https://github.com/DansDesigns/Alternix.git"
VERSION_URL="https://raw.githubusercontent.com/DansDesigns/Alternix/main/update/version.txt"

LOCAL_VERSION=$(cat /usr/share/alternix/version.txt 2>/dev/null)
REMOTE_VERSION=$(curl -fs $VERSION_URL)


while true; do

    LOCAL_VERSION=$(cat /usr/share/alternix/version.txt 2>/dev/null)
    REMOTE_VERSION=$(curl -fs "$VERSION_URL")

    if [ -z "$REMOTE_VERSION" ]; then
        echo ""
        echo "[------ERROR------]"
        echo "Unable to check for updates."
        echo "Check Internet Connection."
        echo ""
        echo "1) Retry"
        echo "2) Exit"
        read -p "Select option: " choice

        if [ "$choice" = "1" ]; then
            clear
            continue
        else
            exit 1
        fi
    fi

    if dpkg --compare-versions "$REMOTE_VERSION" gt "$LOCAL_VERSION"; then
        echo ""
        echo "Update found.."
        echo "Current Version: $LOCAL_VERSION"
        echo "New Version: $REMOTE_VERSION"
        echo ""
        echo "Downloading Update..."

        TMP_DIR=$(mktemp -d) || exit 1

        if ! git clone "$REPO_URL" "$TMP_DIR"; then
            echo "[------ERROR------]"
            echo "Download failed.."
            cd /
            rm -rf "$TMP_DIR"
            
            echo "1) Retry"
            echo "2) Exit"
            read -p "Select option: " choice1

            if [ "$choice1" = "1" ]; then
                clear
                continue
            else
                exit 1
            fi
        fi

        cd "$TMP_DIR" || exit 1

        echo ""
        echo "Download Complete!"
        chmod +x install-update.sh
        echo ""
        echo "Installing Update..."

        if ! ./install-update.sh; then
            echo "[------ERROR------]"
            echo "Installation failed.."
            cd /
            rm -rf "$TMP_DIR"
            
            echo "1) Retry"
            echo "2) Exit"
            read -p "Select option: " choice2

            if [ "$choice2" = "1" ]; then
                clear
                continue
            else
                exit 1
            fi
        fi
        echo "---------------------"
        echo "New Current Version:"
        echo "$REMOTE_VERSION" | sudo tee /usr/share/alternix/version.txt > /dev/null
        echo "---------------------"

        cd /
        echo ""
        echo "Cleaning Installation Crumbs.."
        rm -rf "$TMP_DIR"

        echo ""
        break
    else
        echo " "
        sleep 2
        echo "No Update needed.."
        echo " "
        sleep 1
        echo "Alternix is up to date: $LOCAL_VERSION"
        sleep 5
        break
    fi
done