#!/bin/bash

LOCAL_VERSION=$(cat /usr/share/alternix/version.txt 2>/dev/null)

echo "=============================================="
echo "          Alternix Desktop Updater"
echo "=============================================="
echo " -------> Teaching Penguins to fly! <-------"
echo " "
echo "=============================================="
echo "       Current Version: $LOCAL_VERSION"
echo "=============================================="
echo "Checking for Linux System Updates..."
echo " "
sudo nala update
echo " "
echo "Applying Upgrades…"
echo " "
sudo nala upgrade -y
echo " "
echo "Checking for Alternix Updates..."

REPO_URL="https://github.com/DansDesigns/Alternix.git"
VERSION_URL="https://raw.githubusercontent.com/DansDesigns/Alternix/main/update/version.txt"

REMOTE_VERSION=$(curl -fs $VERSION_URL)

while true; do

    LOCAL_VERSION=$(cat /usr/share/alternix/version.txt 2>/dev/null)
    REMOTE_VERSION=$(curl -fs "$VERSION_URL")

    if [ -z "$REMOTE_VERSION" ]; then
        echo ""
        echo "[------ERROR------]"
        echo "Unable to check for updates."
        echo "Check Internet Connection."
        echo ""
        echo "1) Retry"
        echo "2) Exit"
        read -p "Select option: " choice

        if [ "$choice" = "1" ]; then
            clear
            continue
        else
            exit 1
        fi
    fi

    if dpkg --compare-versions "$REMOTE_VERSION" gt "$LOCAL_VERSION"; then
        echo ""
        echo "New Update found!"
        echo ""
        echo "--------------------------------"
        echo "Current Version: $LOCAL_VERSION"
        echo "New Version: $REMOTE_VERSION"
        echo "--------------------------------"
        echo ""
        echo "Downloading Update..."
        echo ""

        TMP_DIR=$(mktemp -d) || exit 1

        if ! git clone "$REPO_URL" "$TMP_DIR"; then
            echo ""
            echo "[------ERROR------]"
            echo "Download failed.."
            echo ""
            cd /
            rm -rf "$TMP_DIR"
            
            echo "1) Retry"
            echo "2) Exit"
            read -p "Select option: " choice1

            if [ "$choice1" = "1" ]; then
                clear
                continue
            else
                exit 1
            fi
        fi

        cd "$TMP_DIR" || exit 1

        echo ""
        echo "Download Complete!"
        chmod +x install-update.sh
        echo ""
        echo "Installing Update..."
        echo ""

        if ! ./install-update.sh; then
            echo ""
            echo "[------ERROR------]"
            echo "Installation failed.."
            echo ""
            cd /
            rm -rf "$TMP_DIR"
            
            echo "1) Retry"
            echo "2) Exit"
            read -p "Select option: " choice2

            if [ "$choice2" = "1" ]; then
                clear
                continue
            else
                exit 1
            fi
        fi
        echo "=============================================="
        echo "Installed Version:"
        echo "$LOCAL_VERSION" | sudo tee /usr/share/alternix/version.txt > /dev/null
        echo "=============================================="
        echo ""
        sleep 2
        cd /
        echo ""
        echo "Cleaning Installation Crumbs.."
        rm -rf "$TMP_DIR"
        echo ""
        echo "Press 1 to [Reboot]"
        echo "Press 2 to Continue"
        while true; do
            read -n 1 -s -r KEY
            if [[ "$KEY" == "1" ]]; then
                echo "Beginning Reboot Sequence..."
                echo " "
                echo "This window will self-destruct in 5 seconds..."
                sleep 1
                echo "5.."
                sleep 1
                echo "4.."
                sleep 1
                echo "3.."
                sleep 1
                echo "2.."
                sleep 1
                echo "1.."
                sleep 1
                sudo reboot
                break
            elif [[ "$KEY" == "2" ]]; then
                echo ""
                echo "Continuing to shell..."
                sleep 2
                break
            else
                echo ""
                echo "Invalid choice. Press 1 to Restart or 2 to Continue."
            fi
        done
        

    else
        echo " "
        echo "No Update needed."
        echo " "
        echo "Current Version: $LOCAL_VERSION"
        echo " "
        echo "This window will self-destruct in 5 seconds..."
        sleep 1
        echo "5.."
        sleep 1
        echo "4.."
        sleep 1
        echo "3.."
        sleep 1
        echo "2.."
        sleep 1
        echo "1.."
        sleep 1
        break
    fi
done